# Generated by Django 2.0.2 on 2018-05-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_users', '0004_dr_info_adder'),
    ]

    operations = [
        migrations.AddField(
            model_name='dr_info',
            name='Dr_special',
            field=models.CharField(default='', max_length=50),
        ),
    ]
