# Generated by Django 2.0.2 on 2018-05-20 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Super_users', '0005_dr_info_dr_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dr_info',
            name='Dr_special',
        ),
        migrations.AddField(
            model_name='dr_info',
            name='Dr_mobile',
            field=models.CharField(default='-1', max_length=13),
        ),
        migrations.AddField(
            model_name='dr_info',
            name='Dr_specialty',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='dr_info',
            name='Dr_google_map_link',
            field=models.CharField(default='-1', max_length=700),
        ),
        migrations.AlterField(
            model_name='dr_info',
            name='Dr_photo_link',
            field=models.CharField(default='../statics/Picture/Profile/People-Doctor-male-icon.png', max_length=700),
        ),
        migrations.AlterField(
            model_name='dr_info',
            name='Dr_telephone',
            field=models.CharField(default='-1', max_length=11),
        ),
        migrations.AlterField(
            model_name='dr_info',
            name='adder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Super_users.collector'),
        ),
    ]
