# Generated by Django 2.0.2 on 2018-05-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_users', '0008_examplemodel_fuckexamplemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('zipcode', models.CharField(max_length=5)),
                ('comments', models.TextField()),
                ('image', models.ImageField(upload_to='survey_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.DeleteModel(
            name='FuckExampleModel',
        ),
    ]
