# Generated by Django 2.0.2 on 2018-05-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Super_users', '0009_auto_20180524_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='survey_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Super_users.RelatedImage')),
            ],
        ),
        migrations.RemoveField(
            model_name='survey',
            name='image',
        ),
        migrations.AddField(
            model_name='surveyimage',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Super_users.Survey'),
        ),
    ]
