# Generated by Django 2.0.2 on 2018-05-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_users', '0010_auto_20180524_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='surveyimage',
            name='survey',
        ),
        migrations.DeleteModel(
            name='RelatedImage',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='SurveyImage',
        ),
    ]
