# Generated by Django 2.0.2 on 2018-05-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_users', '0012_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
    ]
