# Generated by Django 2.0.2 on 2018-05-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_users', '0015_auto_20180527_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='hash_capcha',
            name='Number_name',
            field=models.CharField(default='-1', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='hash_capcha',
            name='Hash_value',
            field=models.CharField(default='-1', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='hash_capcha',
            name='Number',
            field=models.CharField(default='-1', max_length=13, unique=True),
        ),
    ]
