# Generated by Django 2.0.2 on 2018-05-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_users', '0016_auto_20180527_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialiy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialiy_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
