# Generated by Django 2.0.5 on 2018-06-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_users', '0017_specialiy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr_info',
            name='Dr_photo_link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
