# Generated by Django 2.0.5 on 2018-06-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_users', '0018_auto_20180620_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iran_city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
