# Generated by Django 2.0.5 on 2018-06-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_users', '0019_iran_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr_info',
            name='Dr_photo_link',
            field=models.CharField(default='/media/People-Doctor-Male-icon.png', max_length=1000),
        ),
    ]
